=== myTeachingURJC/2021-2022-LTAW/S04/Ejemplos/tienda.dtd
<!-- Documento de definicion de mi tienda -->

<!-- Elemento raiz -->
<!-- La tienda esta compuesta de productos:  
     Ninguno, uno o muchos                  -->
<!ELEMENT tienda (producto*)>

<!-- La descripcion de los productos es opcional -->
<!ELEMENT producto (nombre, descripcion?, stock)>

<!-- Elementos simples -->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT stock (#PCDATA)>

=== myTeachingURJC/2021-2022-LTAW/S04/Ejemplos/05-tienda.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Definicion de mi tienda -->
<!DOCTYPE tienda SYSTEM "tienda.dtd">

<tienda>
    <producto>
        <nombre>Alhambra II</nombre>
        <descripcion>Placa con FPGA ice40HX8K</descripcion>
        <stock>3</stock>
    </producto>

    <producto>
        <nombre>Icestick</nombre>
        <stock>10</stock>
    </producto>
</tienda>
